package csz.mdm.dto;

/**Auto Generated By Hap Code Generator**/
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import com.hand.hap.mybatis.annotation.ExtensionAttribute;
import org.hibernate.validator.constraints.Length;
import javax.persistence.Table;
import com.hand.hap.system.dto.BaseDTO;
import java.util.Date;
import org.hibernate.validator.constraints.NotEmpty;
@ExtensionAttribute(disable=true)
@Table(name = "xx_mdm_answer")
public class MdmAnswer extends BaseDTO {

     public static final String FIELD_ANSWER_ID = "answerId";
     public static final String FIELD_QUESTION_ID = "questionId";
     public static final String FIELD_QUESTION_TYPE = "questionType";
     public static final String FIELD_ANSWER = "answer";
     public static final String FIELD_PROGRAM_APPLICATION_ID = "programApplicationId";
     public static final String FIELD_PROGRAM_UPDATE_DATE = "programUpdateDate";


     @Id
     @GeneratedValue
     private Long answerId; //表id

     private Long questionId; //题目id

     @Length(max = 240)
     private String questionType; //题目类型

     @NotEmpty
     @Length(max = 240)
     private String answer; //答案

     private Long programApplicationId;

     private Date programUpdateDate;


     public void setAnswerId(Long answerId){
         this.answerId = answerId;
     }

     public Long getAnswerId(){
         return answerId;
     }

     public void setQuestionId(Long questionId){
         this.questionId = questionId;
     }

     public Long getQuestionId(){
         return questionId;
     }

     public void setQuestionType(String questionType){
         this.questionType = questionType;
     }

     public String getQuestionType(){
         return questionType;
     }

     public void setAnswer(String answer){
         this.answer = answer;
     }

     public String getAnswer(){
         return answer;
     }

     public void setProgramApplicationId(Long programApplicationId){
         this.programApplicationId = programApplicationId;
     }

     public Long getProgramApplicationId(){
         return programApplicationId;
     }

     public void setProgramUpdateDate(Date programUpdateDate){
         this.programUpdateDate = programUpdateDate;
     }

     public Date getProgramUpdateDate(){
         return programUpdateDate;
     }

     }
