package csz.mdm.dto;

/**Auto Generated By Hap Code Generator**/
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import com.hand.hap.mybatis.annotation.ExtensionAttribute;
import org.hibernate.validator.constraints.Length;
import javax.persistence.Table;
import javax.persistence.Transient;

import com.hand.hap.system.dto.BaseDTO;
import java.util.Date;
import org.hibernate.validator.constraints.NotEmpty;
@ExtensionAttribute(disable=true)
@Table(name = "xx_mdm_class")
public class MdmClass extends BaseDTO {

     public static final String FIELD_CLASS_ID = "classId";
     public static final String FIELD_CLASS_NAME = "className";
     public static final String FIELD_CLASS_CODE = "classCode";
     public static final String FIELD_COURSE_ID = "courseId";
     public static final String FIELD_USER_ID = "userId";
     public static final String FIELD_CLASS_NUMBER = "classNumber";
     public static final String FIELD_CLASS_DESCRIPTION = "classDescription";
     public static final String FIELD_PROGRAM_APPLICATION_ID = "programApplicationId";
     public static final String FIELD_PROGRAM_UPDATE_DATE = "programUpdateDate";


     @Id
     @GeneratedValue
     private Long classId; //表ID

     @NotEmpty
     @Length(max = 240)
     private String className; //名称

     @Length(max = 240)
     private String classCode; //编码

     private Long courseId; //课程id

     @Length(max = 240)
     private String userId; //创建者id

     private Long classNumber; //人数

     @Length(max = 240)
     private String classDescription; //描述

     private Long programApplicationId;

     private Date programUpdateDate;

     @Transient
     private String courseName;//课程名称

    public String getCourseName() {
        return courseName;
    }

    public void setCourseName(String courseName) {
        this.courseName = courseName;
    }

    public void setClassId(Long classId){
         this.classId = classId;
     }

     public Long getClassId(){
         return classId;
     }

     public void setClassName(String className){
         this.className = className;
     }

     public String getClassName(){
         return className;
     }

     public void setClassCode(String classCode){
         this.classCode = classCode;
     }

     public String getClassCode(){
         return classCode;
     }

     public void setCourseId(Long courseId){
         this.courseId = courseId;
     }

     public Long getCourseId(){
         return courseId;
     }

     public void setUserId(String userId){
         this.userId = userId;
     }

     public String getUserId(){
         return userId;
     }

     public void setClassNumber(Long classNumber){
         this.classNumber = classNumber;
     }

     public Long getClassNumber(){
         return classNumber;
     }

     public void setClassDescription(String classDescription){
         this.classDescription = classDescription;
     }

     public String getClassDescription(){
         return classDescription;
     }

     public void setProgramApplicationId(Long programApplicationId){
         this.programApplicationId = programApplicationId;
     }

     public Long getProgramApplicationId(){
         return programApplicationId;
     }

     public void setProgramUpdateDate(Date programUpdateDate){
         this.programUpdateDate = programUpdateDate;
     }

     public Date getProgramUpdateDate(){
         return programUpdateDate;
     }

     }
