package csz.mdm.dto;

/**Auto Generated By Hap Code Generator**/
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import com.hand.hap.mybatis.annotation.ExtensionAttribute;
import org.hibernate.validator.constraints.Length;
import javax.persistence.Table;
import javax.persistence.Transient;

import com.hand.hap.system.dto.BaseDTO;
import java.util.Date;
import org.hibernate.validator.constraints.NotEmpty;
@ExtensionAttribute(disable=true)
@Table(name = "xx_mdm_course")
public class MdmCourse extends BaseDTO {

     public static final String FIELD_COURSE_ID = "courseId";
     public static final String FIELD_COURSE_NAME = "courseName";
     public static final String FIELD_COURSE_CODE = "courseCode";
     public static final String FIELD_USER_ID = "userId";
     public static final String FIELD_COURSE_DESCRIPTION = "courseDescription";
     public static final String FIELD_COURSE_NUMBER = "courseNumber";
     public static final String FIELD_COURSE_START_DATE = "courseStartDate";
     public static final String FIELD_COURSE_END_DATE = "courseEndDate";
     public static final String FIELD_COURSE_CREDIT = "courseCredit";
     public static final String FIELD_PROGRAM_APPLICATION_ID = "programApplicationId";
     public static final String FIELD_PROGRAM_UPDATE_DATE = "programUpdateDate";


     @Id
     @GeneratedValue
     private Long courseId; //表id

     @NotEmpty
     @Length(max = 240)
     private String courseName; //名称

     @NotEmpty
     @Length(max = 240)
     private String courseCode; //编码

     @NotEmpty
     @Length(max = 240)
     private String userId; //创建者id

     @Length(max = 240)
     private String courseDescription; //描述

     private Long courseNumber; //人数

     private Date courseStartDate; //开课

     private Date courseEndDate; //账户

     private Long courseCredit; //学分

     private Long programApplicationId;

     private Date programUpdateDate;

     @Transient
     private String studentName;
     @Transient
     private String studentCode;
     @Transient
     private String studentId;

    public String getStudentId() {
        return studentId;
    }

    public void setStudentId(String studentId) {
        this.studentId = studentId;
    }

    public String getStudentCode() {
        return studentCode;
    }

    public void setStudentCode(String studentCode) {
        this.studentCode = studentCode;
    }

    public String getStudentName() {
        return studentName;
    }

    public void setStudentName(String studentName) {
        this.studentName = studentName;
    }

    public void setCourseId(Long courseId){
         this.courseId = courseId;
     }

     public Long getCourseId(){
         return courseId;
     }

     public void setCourseName(String courseName){
         this.courseName = courseName;
     }

     public String getCourseName(){
         return courseName;
     }

     public void setCourseCode(String courseCode){
         this.courseCode = courseCode;
     }

     public String getCourseCode(){
         return courseCode;
     }

     public void setUserId(String userId){
         this.userId = userId;
     }

     public String getUserId(){
         return userId;
     }

     public void setCourseDescription(String courseDescription){
         this.courseDescription = courseDescription;
     }

     public String getCourseDescription(){
         return courseDescription;
     }

     public void setCourseNumber(Long courseNumber){
         this.courseNumber = courseNumber;
     }

     public Long getCourseNumber(){
         return courseNumber;
     }

     public void setCourseStartDate(Date courseStartDate){
         this.courseStartDate = courseStartDate;
     }

     public Date getCourseStartDate(){
         return courseStartDate;
     }

     public void setCourseEndDate(Date courseEndDate){
         this.courseEndDate = courseEndDate;
     }

     public Date getCourseEndDate(){
         return courseEndDate;
     }

     public void setCourseCredit(Long courseCredit){
         this.courseCredit = courseCredit;
     }

     public Long getCourseCredit(){
         return courseCredit;
     }

     public void setProgramApplicationId(Long programApplicationId){
         this.programApplicationId = programApplicationId;
     }

     public Long getProgramApplicationId(){
         return programApplicationId;
     }

     public void setProgramUpdateDate(Date programUpdateDate){
         this.programUpdateDate = programUpdateDate;
     }

     public Date getProgramUpdateDate(){
         return programUpdateDate;
     }

     }
