package csz.mdm.dto;

/**Auto Generated By Hap Code Generator**/
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import com.hand.hap.mybatis.annotation.ExtensionAttribute;
import org.hibernate.validator.constraints.Length;
import javax.persistence.Table;
import com.hand.hap.system.dto.BaseDTO;
import java.util.Date;
@ExtensionAttribute(disable=true)
@Table(name = "xx_mdm_class_time")
public class MdmClassTime extends BaseDTO {

     public static final String FIELD_CLASS_TIEM_ID = "classTiemId";
     public static final String FIELD_CLASS_ID = "classId";
     public static final String FIELD_CLASS_START_TIME = "classStartTime";
     public static final String FIELD_CLASS_END_TIME = "classEndTime";
     public static final String FIELD_PROGRAM_APPLICATION_ID = "programApplicationId";
     public static final String FIELD_PROGRAM_UPDATE_DATE = "programUpdateDate";


     @Id
     @GeneratedValue
     private Long classTiemId; //表id

     private Long classId;

     private Date classStartTime; //上课时间

     private Date classEndTime; //下课时间

     private Long programApplicationId;

     private Date programUpdateDate;


     public void setClassTiemId(Long classTiemId){
         this.classTiemId = classTiemId;
     }

     public Long getClassTiemId(){
         return classTiemId;
     }

     public void setClassId(Long classId){
         this.classId = classId;
     }

     public Long getClassId(){
         return classId;
     }

     public void setClassStartTime(Date classStartTime){
         this.classStartTime = classStartTime;
     }

     public Date getClassStartTime(){
         return classStartTime;
     }

     public void setClassEndTime(Date classEndTime){
         this.classEndTime = classEndTime;
     }

     public Date getClassEndTime(){
         return classEndTime;
     }

     public void setProgramApplicationId(Long programApplicationId){
         this.programApplicationId = programApplicationId;
     }

     public Long getProgramApplicationId(){
         return programApplicationId;
     }

     public void setProgramUpdateDate(Date programUpdateDate){
         this.programUpdateDate = programUpdateDate;
     }

     public Date getProgramUpdateDate(){
         return programUpdateDate;
     }

     }
