package csz.mdm.dto;

/**
 * Auto Generated By Hap Code Generator
 **/

import javax.persistence.GeneratedValue;
import javax.persistence.Id;

import com.hand.hap.mybatis.annotation.ExtensionAttribute;
import org.hibernate.validator.constraints.Length;

import javax.persistence.Table;
import javax.persistence.Transient;

import com.hand.hap.system.dto.BaseDTO;

import java.util.Date;

import org.hibernate.validator.constraints.NotEmpty;

@ExtensionAttribute(disable = true)
@Table(name = "xx_mdm_question")
public class MdmQuestion extends BaseDTO {

    public static final String FIELD_QUESTION_ID = "questionId";
    public static final String FIELD_COURSE_ID = "courseId";
    public static final String FIELD_USER_ID = "userId";
    public static final String FIELD_QUESTION_CODE = "questionCode";
    public static final String FIELD_QUESTION_STEM = "questionStem";
    public static final String FIELD_QUESTION_IS_SHARE = "questionIsShare";
    public static final String FIELD_QUESTION_DESCRIPTION = "questionDescription";
    public static final String FIELD_QUESTION_TYPE = "questionType";
    public static final String FIELD_OPTION1 = "option1";
    public static final String FIELD_OPTION2 = "option2";
    public static final String FIELD_OPTION3 = "option3";
    public static final String FIELD_OPTION4 = "option4";
    public static final String FIELD_OPTION5 = "option5";
    public static final String FIELD_OPTION6 = "option6";
    public static final String FIELD_OPTION7 = "option7";
    public static final String FIELD_OPTION8 = "option8";
    public static final String FIELD_PROGRAM_APPLICATION_ID = "programApplicationId";
    public static final String FIELD_PROGRAM_UPDATE_DATE = "programUpdateDate";


    @Id
    @GeneratedValue
    private Long questionId; //表id

    private Long courseId; //课程id

    @NotEmpty
    @Length(max = 240)
    private String userId; //创建者id

    @NotEmpty
    @Length(max = 240)
    private String questionCode; //问题编码

    @NotEmpty
    @Length(max = 4000)
    private String questionStem; //题干

    @Length(max = 240)
    private String questionIsShare; //是否共享

    @Length(max = 500)
    private String questionDescription; //描述

    @NotEmpty
    @Length(max = 240)
    private String questionType; //题型

    @Length(max = 240)
    private String option1;

    @Length(max = 240)
    private String option2;

    @Length(max = 240)
    private String option3;

    @Length(max = 240)
    private String option4;

    @Length(max = 240)
    private String option5;

    @Length(max = 240)
    private String option6;

    @Length(max = 240)
    private String option7;

    @Length(max = 240)
    private String option8;

    @Transient
    private String courseName;//课程名称

    @Transient
    private Long score; //得分
    @Transient
    private Long studentId;
    @Transient
    private Long classId;

    public Long getClassId() {
        return classId;
    }

    public void setClassId(Long classId) {
        this.classId = classId;
    }

    public Long getStudentId() {
        return studentId;
    }

    public void setStudentId(Long studentId) {
        this.studentId = studentId;
    }

    public Long getScore() {
        return score;
    }

    public void setScore(Long score) {
        this.score = score;
    }

    public String getCourseName() {
        return courseName;
    }

    public void setCourseName(String courseName) {
        this.courseName = courseName;
    }

    private Long programApplicationId;

    private Date programUpdateDate;


    public void setQuestionId(Long questionId) {
        this.questionId = questionId;
    }

    public Long getQuestionId() {
        return questionId;
    }

    public void setCourseId(Long courseId) {
        this.courseId = courseId;
    }

    public Long getCourseId() {
        return courseId;
    }

    public String getUserId() {
        return userId;
    }

    public void setUserId(String userId) {
        this.userId = userId;
    }

    public String getQuestionCode() {
        return questionCode;
    }

    public void setQuestionCode(String questionCode) {
        this.questionCode = questionCode;
    }

    public void setQuestionStem(String questionStem) {
        this.questionStem = questionStem;
    }

    public String getQuestionStem() {
        return questionStem;
    }

    public void setQuestionIsShare(String questionIsShare) {
        this.questionIsShare = questionIsShare;
    }

    public String getQuestionIsShare() {
        return questionIsShare;
    }

    public String getQuestionDescription() {
        return questionDescription;
    }

    public void setQuestionDescription(String questionDescription) {
        this.questionDescription = questionDescription;
    }

    public void setQuestionType(String questionType) {
        this.questionType = questionType;
    }

    public String getQuestionType() {
        return questionType;
    }

    public void setOption1(String option1) {
        this.option1 = option1;
    }

    public String getOption1() {
        return option1;
    }

    public void setOption2(String option2) {
        this.option2 = option2;
    }

    public String getOption2() {
        return option2;
    }

    public void setOption3(String option3) {
        this.option3 = option3;
    }

    public String getOption3() {
        return option3;
    }

    public void setOption4(String option4) {
        this.option4 = option4;
    }

    public String getOption4() {
        return option4;
    }

    public void setOption5(String option5) {
        this.option5 = option5;
    }

    public String getOption5() {
        return option5;
    }

    public void setOption6(String option6) {
        this.option6 = option6;
    }

    public String getOption6() {
        return option6;
    }

    public void setOption7(String option7) {
        this.option7 = option7;
    }

    public String getOption7() {
        return option7;
    }

    public void setOption8(String option8) {
        this.option8 = option8;
    }

    public String getOption8() {
        return option8;
    }

    public void setProgramApplicationId(Long programApplicationId) {
        this.programApplicationId = programApplicationId;
    }

    public Long getProgramApplicationId() {
        return programApplicationId;
    }

    public void setProgramUpdateDate(Date programUpdateDate) {
        this.programUpdateDate = programUpdateDate;
    }

    public Date getProgramUpdateDate() {
        return programUpdateDate;
    }

}
