package csz.mdm.dto;

/**Auto Generated By Hap Code Generator**/
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import com.hand.hap.mybatis.annotation.ExtensionAttribute;
import org.hibernate.validator.constraints.Length;
import javax.persistence.Table;
import com.hand.hap.system.dto.BaseDTO;
import java.util.Date;
@ExtensionAttribute(disable=true)
@Table(name = "xx_mdm_question_image")
public class MdmQuestionImage extends BaseDTO {

     public static final String FIELD_QUESTION_IMAGE_ID = "questionImageId";
     public static final String FIELD_QUESTION_ID = "questionId";
     public static final String FIELD_IMAGE_URL = "imageUrl";
     public static final String FIELD_IMAGE_SEQUENCE = "imageSequence";
     public static final String FIELD_PROGRAM_APPLICATION_ID = "programApplicationId";
     public static final String FIELD_PROGRAM_UPDATE_DATE = "programUpdateDate";


     @Id
     @GeneratedValue
     private Long questionImageId; //表id

     private Long questionId; //问题id

     @Length(max = 1000)
     private String imageUrl; //图片地址

     private Long imageSequence; //序列

     private Long programApplicationId;

     private Date programUpdateDate;


     public void setQuestionImageId(Long questionImageId){
         this.questionImageId = questionImageId;
     }

     public Long getQuestionImageId(){
         return questionImageId;
     }

     public void setQuestionId(Long questionId){
         this.questionId = questionId;
     }

     public Long getQuestionId(){
         return questionId;
     }

     public void setImageUrl(String imageUrl){
         this.imageUrl = imageUrl;
     }

     public String getImageUrl(){
         return imageUrl;
     }

     public void setImageSequence(Long imageSequence){
         this.imageSequence = imageSequence;
     }

     public Long getImageSequence(){
         return imageSequence;
     }

     public void setProgramApplicationId(Long programApplicationId){
         this.programApplicationId = programApplicationId;
     }

     public Long getProgramApplicationId(){
         return programApplicationId;
     }

     public void setProgramUpdateDate(Date programUpdateDate){
         this.programUpdateDate = programUpdateDate;
     }

     public Date getProgramUpdateDate(){
         return programUpdateDate;
     }

     }
