package csz.mdm.dto;

/**Auto Generated By Hap Code Generator**/
import javax.persistence.GeneratedValue;
import javax.persistence.Id;

import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.hand.hap.mybatis.annotation.ExtensionAttribute;
import org.hibernate.validator.constraints.Length;
import javax.persistence.Table;
import com.hand.hap.system.dto.BaseDTO;
import java.util.Date;
import org.hibernate.validator.constraints.NotEmpty;
@ExtensionAttribute(disable=true)
@Table(name = "xx_mdm_user")
@JsonDeserialize
public class MdmUser extends BaseDTO {

     public static final String FIELD_USER_ID = "userId";
     public static final String FIELD_USER_NAME = "userName";
     public static final String FIELD_USER_CODE = "userCode";
     public static final String FIELD_USER_PHONE = "userPhone";
     public static final String FIELD_USER_EMAIL = "userEmail";
     public static final String FIELD_USER_PASSWORD = "userPassword";
     public static final String FIELD_USER_ROLE = "userRole";
     public static final String FIELD_PROGRAM_APPLICATION_ID = "programApplicationId";
     public static final String FIELD_PROGRAM_UPDATE_DATE = "programUpdateDate";


     @Id
     @GeneratedValue
     private Long userId; //表ID

     @NotEmpty
     @Length(max = 240)
     private String userName; //姓名

     @NotEmpty
     @Length(max = 240)
     private String userCode; //编码

     @NotEmpty
     @Length(max = 240)
     private String userPhone; //手机

     @NotEmpty
     @Length(max = 240)
     private String userEmail; //邮箱

     @NotEmpty
     @Length(max = 240)
     private String userPassword; //密码


     private Long userRole; //角色

     private Long programApplicationId;

     private Date programUpdateDate;


     public void setUserId(Long userId){
         this.userId = userId;
     }

     public Long getUserId(){
         return userId;
     }

     public void setUserName(String userName){
         this.userName = userName;
     }

     public String getUserName(){
         return userName;
     }

     public void setUserCode(String userCode){
         this.userCode = userCode;
     }

     public String getUserCode(){
         return userCode;
     }

     public void setUserPhone(String userPhone){
         this.userPhone = userPhone;
     }

     public String getUserPhone(){
         return userPhone;
     }

     public void setUserEmail(String userEmail){
         this.userEmail = userEmail;
     }

     public String getUserEmail(){
         return userEmail;
     }

     public void setUserPassword(String userPassword){
         this.userPassword = userPassword;
     }

     public String getUserPassword(){
         return userPassword;
     }

    public Long getUserRole() {
        return userRole;
    }

    public void setUserRole(Long userRole) {
        this.userRole = userRole;
    }

    public void setProgramApplicationId(Long programApplicationId){
         this.programApplicationId = programApplicationId;
     }

     public Long getProgramApplicationId(){
         return programApplicationId;
     }

     public void setProgramUpdateDate(Date programUpdateDate){
         this.programUpdateDate = programUpdateDate;
     }

     public Date getProgramUpdateDate(){
         return programUpdateDate;
     }

    @Override
    public String toString() {
        return "MdmUser{" +
                "userId=" + userId +
                ", userName='" + userName + '\'' +
                ", userCode='" + userCode + '\'' +
                ", userPhone='" + userPhone + '\'' +
                ", userEmail='" + userEmail + '\'' +
                ", userPassword='" + userPassword + '\'' +
                ", userRole=" + userRole +
                ", programApplicationId=" + programApplicationId +
                ", programUpdateDate=" + programUpdateDate +
                '}';
    }
}
