create table sys_user
(
 user_id int not null auto_increment comment '表id',
 user_code varchar(20) not null comment '用户编码',
 user_name varchar(100) not null comment '名称',
 user_type varchar(100) comment '用户类型',
 password_encryption varchar(100) not null comment '加密密码',
 description varchar(240) comment '描述',
 email varchar(100) comment '邮箱',
 qq varchar(100) comment 'qq',
 wechat varchar(100) comment '微信',
 phone varchar(100) comment '手机',
 status varchar(100) comment '状态',
 first_login varchar(1) default 'y' not null comment '是否是第一次登陆',
 start_active_date date comment '有效期从',
 end_active_data date comment '有兴趣至',
 create_date date comment '创建日期',
 update_date date comment '更新日期',
 last_password_update_date date comment '最后更新密码日期',
 last_login_date date comment '最后登陆日期',
 creation_date datetime default current_timestamp not null,
 created_by int default -1 not null,
 last_updated_by int default -1 not null,
 last_update_date datetime default current_timestamp not null,
 last_update_login int,
 program_application_id int,
 program_id int,
 program_update_date date,
 request_id int,
 attribute_category varchar(30),
 attribute1 varchar(240),
 attribute2 varchar(240),
 attribute3 varchar(240),
 attribute4 varchar(240),
 attribute5 varchar(240),
 attribute6 varchar(240),
 attribute7 varchar(240),
 attribute8 varchar(240),
 attribute9 varchar(240),
 attribute10 varchar(240),
 attribute11 varchar(240),
 attribute12 varchar(240),
 attribute13 varchar(240),
 attribute14 varchar(240),
 attribute15 varchar(240), primary key (user_id)
)   comment '用户表';


create index sys_user_n1 on sys_user(user_code,user_type);
create index sys_user_n2 on sys_user(user_id);