create table sf_dev.xx_course
(
 course_id int not null auto_increment comment '表id',
 course_code varchar(100) not null comment '课程编码',
 course_name varchar(100) not null comment '课程名称',
 user_id int not null comment '教师id',
 course_description varchar(240) comment '课程描述',
 course_start_date date not null comment '开课时间',
 course_end_date date not null comment '结课时间',
 course_credit int comment '学分',
 update_date varchar(1) not null comment '更新时间',
 create_date varchar(1) not null comment '创建时间',
 creation_date datetime default current_timestamp not null,
 created_by int default -1 not null,
 last_updated_by int default -1 not null,
 last_update_date datetime default current_timestamp not null,
 last_update_login int,
 program_application_id int,
 program_id int,
 program_update_date date,
 request_id int,
 attribute_category varchar(30),
 attribute1 varchar(240),
 attribute2 varchar(240),
 attribute3 varchar(240),
 attribute4 varchar(240),
 attribute5 varchar(240),
 attribute6 varchar(240),
 attribute7 varchar(240),
 attribute8 varchar(240),
 attribute9 varchar(240),
 attribute10 varchar(240),
 attribute11 varchar(240),
 attribute12 varchar(240),
 attribute13 varchar(240),
 attribute14 varchar(240),
 attribute15 varchar(240), primary key (course_id)
)   comment '课程表';


create index xx_course_n1 on sf_dev.xx_course(user_id,course_id);